@baseUrl= http://localhost:5000/api
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5NTNiOThmN2YzNDgyZGQ3YWE4MDhhYSIsInJvbGUiOiI2OTUzYjdmMTM0ODBmYmUwMjlkNzhlMzciLCJ3YXJlSG91c2UiOiI2OTUyMGU0NWZkYjU5ZGZlMjQ4NTZiMzUiLCJpYXQiOjE3NjcwOTQ4MzAsImV4cCI6MTc2NzE4MTIzMH0.y3zpgeQTKmwsLTHQckteeC787NgEzbVu89jMiIaCIGU
###create customer group
POST {{baseUrl}}/customerGroup
Content-Type: application/json

{
    "name":"VIP Customer",
    "discount":10,
    "description":"VIP Customer",
    "location":1,
    "isDeleted":false
}

###get all customerGroup
GET {{baseUrl}}/customerGroup
Content-Type: application/json

###get customerGroup by id
GET {{baseUrl}}/customerGroup/6950b94cb26e3846216c3359
Content-Type: application/json

###update customerGroup by id
PUT {{baseUrl}}/customerGroup/6950b94cb26e3846216c3359
Content-Type: application/json

{
    "name":"VIP Customer Updated"
}

###delete customerGroup by id
DELETE {{baseUrl}}/customerGroup/6950b94cb26e3846216c3359
Content-Type: application/json

###create customer
POST {{baseUrl}}/customer
Content-Type: application/json

{
  "name": "Ram Basnet",
  "company": "JD Enterprises",
  "phone": "+9779876543210",
  "email": "ram.basnet@example.com",
  "address": "123 Main Street",
  "city": "Kathmandu",
  "region": "Bagmati",
  "country": "Nepal",
  "postbox": "44600",
  "shipping": {
    "name": "Sita Basnet",
    "phone": "+9779876543211",
    "address": "124 Main Street",
    "city": "Lalitpur",
    "region": "Bagmati",
    "country": "Nepal",
    "postbox": "44601"
  },
  "customerGroup": "6950b94cb26e3846216c3359",
  "taxid": "123456789",
  "documentId": "DOC123",
  "customField": { "note": "VIP customer" },
  "discount": 10.5,
  "balance": 200.75,
  "picture": "example.png",
  "location": 1,
  "isDeleted": false
}

###get all customers
GET {{baseUrl}}/customer
Content-Type: application/json

###get customer by id
GET {{baseUrl}}/customer/6950bc5a1f946e639b8d9188
Content-Type: application/json

###update customer by id
PUT {{baseUrl}}/customer/6950bc5a1f946e639b8d9188
Content-Type: application/json

{
    "name":"Ram Basnet Updated"
}

###delete customer by id
DELETE {{baseUrl}}/customer/6950bc5a1f946e639b8d9188
Content-Type: application/json



###create supplier Group
POST {{baseUrl}}/supplierGroup
Content-Type: application/json

{
    "name":"VIP Supplier",
    "discount":10,
    "description":"VIP Supplier",
    "location":1,
    "isDeleted":false
} 

###get all supplierGroup
GET {{baseUrl}}/supplierGroup
Content-Type: application/json

###get supplierGroup by id
GET {{baseUrl}}/supplierGroup/6950d2c58794d8998175848f
Content-Type: application/json

###update supplierGroup
PUT {{baseUrl}}/supplierGroup/6950d2c58794d8998175848f
Content-Type: application/json

{
    "name":"VIP Supplier Updated"
}

###delete supplierGroup
DELETE {{baseUrl}}/supplierGroup/6950d2c58794d8998175848f
Content-Type: application/json


###create supplier
POST {{baseUrl}}/supplier
Content-Type: application/json

{
  "name": "supplier1",
  "company": "ABC Trading",
  "phone": "+9779812345678",
  "email": "supplier@example.com",
  "address": "456 Industrial Area",
  "city": "Kathmandu",
  "region": "Bagmati",
  "country": "Nepal",
  "postbox": "44600",
  "supplierGroup": "6950d2c58794d8998175848f",
  "taxId": "TAX123456",
  "documentId": "DOC456",
  "customField": { "note": "Preferred supplier" },
  "discount": 5,
  "balance": 1000,
  "picture": "example.png",
  "isDeleted": false
}

###get all suppliers
GET {{baseUrl}}/supplier
Content-Type: application/json

###get supplier by id
GET {{baseUrl}}/supplier/6950d44c8794d89981758496
Content-Type: application/json

###update supplier by id
PUT {{baseUrl}}/supplier/6950d44c8794d89981758496
Content-Type: application/json

{
    "name":"supplier1 Updated",
    "phone":"+9779812345678",
    "email":"supplier@example.com"
}

###delete supplier by id
DELETE {{baseUrl}}/supplier/6950d44c8794d89981758496
Content-Type: application/json  


###create product category
POST {{baseUrl}}/productCategory
Content-Type: application/json

{
  "title": "Electronics",
  "extra": "Electronic items"
}

###get all product categories
GET {{baseUrl}}/productCategory
Content-Type: application/json

###get product category by id
GET {{baseUrl}}/productCategory/6951455144b4455a47df413e
Content-Type: application/json

###update product category
PUT {{baseUrl}}/productCategory/6951455144b4455a47df413e
Content-Type: application/json

{
    "title":"Electronics Updated",
    "extra":"Electronic items Updated"
}

###delete product category
DELETE {{baseUrl}}/productCategory/6951455144b4455a47df413e
Content-Type: application/json


###create wareHouse
POST {{baseUrl}}/wareHouse
Content-Type: application/json

{
    "title":"WareHouse1",
    "extra":"WareHouse1",
    "location":1,
    "isDeleted":false
}

###get all wareHouses
GET {{baseUrl}}/wareHouse
Content-Type: application/json

###get wareHouse by id
GET {{baseUrl}}/wareHouse/69520e45fdb59dfe24856b35
Content-Type: application/json

###update warehouse
PUT {{baseUrl}}/wareHouse/69520e45fdb59dfe24856b35
Content-Type: application/json

{
    "title":"WareHouse1 Updated",
    "extra":"WareHouse1 Updated",
    "location":1,
    "isDeleted":false
} 

###delete warehouse
DELETE {{baseUrl}}/wareHouse/69520e45fdb59dfe24856b35
Content-Type: application/json

###create productVariation
POST {{baseUrl}}/productVariation
Content-Type: application/json

{
    "name":"size"
} 

###get all productVariation
GET {{baseUrl}}/productVariation
Content-Type: application/json

###get productVariationById
GET {{baseUrl}}/productVariation/69525ed2985343cc9144e1d0
Content-Type: application/json

###update productVariationById
PUT {{baseUrl}}/productVariation/69525ed2985343cc9144e1d0
Content-Type: application/json

{
    "name":"size Updated"
}

###delete productVariationById
DELETE {{baseUrl}}/productVariation/69525ed2985343cc9144e1d0
Content-Type: application/json  

###create productVariationOption
POST {{baseUrl}}/productVariationOption
Content-Type: application/json

{
    "variation":"69525ed2985343cc9144e1d0",
    "value":"xl"
}

###get all productVariationOption
GET {{baseUrl}}/productVariationOption
Content-Type: application/json

###get productVariationOptionByVariationId
GET {{baseUrl}}/productVariationOption/variation/69525ed2985343cc9144e1d0
Content-Type: application/json

###get productVariationOptionById
GET {{baseUrl}}/productVariationOption/69535331adf1287b416a5b74
Content-Type: application/json

###update productVariationOptionById
PUT {{baseUrl}}/productVariationOption/69535331adf1287b416a5b74
Content-Type: application/json

{
    "variation":"69525ed2985343cc9144e1d0",
    "value":"xl Updated"
}

###delete productVariationOptionById
DELETE {{baseUrl}}/productVariationOption/69535331adf1287b416a5b74
Content-Type: application/json

###create product
POST {{baseUrl}}/product
Content-Type: application/json

{
  "product_name":"product1",
  "product_code":"shoe145",
  "product_price":"1200",
  "fproduct_price":"1500",
  "qty":"10",
  "product_category":"6951455144b4455a47df413e",
  "wareHouse":"69520e45fdb59dfe24856b35",
  "taxrate":"10",
  "disrate":"5",
  "product_image":"shoe145.jpg",
  "product_description":"shoe145",
  "alert":"5",
  "unit":"pair",
  "expiry":"2025-12-31",
  "code_type":"EAN13",
  "variation_id": "69525ed2985343cc9144e1d0",
  "variation_option_id": "69535331adf1287b416a5b74"
}

###create product(permission)
POST {{baseUrl}}/product
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "product_name":"shoes",
  "product_code":"shoe145",
  "product_price":"1200",
  "fproduct_price":"1500",
  "qty":"10",
  "product_category":"6951455144b4455a47df413e",
  "wareHouse":"69520e45fdb59dfe24856b35",
  "taxrate":"10",
  "disrate":"5",
  "product_image":"shoe145.jpg",
  "product_description":"shoe145",
  "alert":"5",
  "unit":"pair",
  "expiry":"2025-12-31",
  "code_type":"EAN13",
  "variation_id": "69525ed2985343cc9144e1d0",
  "variation_option_id": "69535331adf1287b416a5b74"
}

###get all products
GET {{baseUrl}}/product
Content-Type: application/json
Authorization: Bearer {{token}}

###get product by id
GET {{baseUrl}}/product/695358924e50688bb9b2a7a1
Content-Type: application/json
Authorization: Bearer {{token}}

###update product
PUT {{baseUrl}}/product/695358924e50688bb9b2a7a1
Content-Type: application/json

{
    "product_name":"product1 Updated"
}

###delete product
DELETE {{baseUrl}}/product/695358924e50688bb9b2a7a1
Content-Type: application/json

### Create Role - Admin
POST {{baseUrl}}/role
Content-Type: application/json

{
  "name": "Admin",
  "permissions": [
    {
      "module": "product",
      "actions": {
        "create": true,
        "read": true,
        "update": true,
        "delete": true
      }
    },
    {
      "module": "customer",
      "actions": {
        "create": true,
        "read": true,
        "update": true,
        "delete": true
      }
    },
    {
      "module": "sale",
      "actions": {
        "create": true,
        "read": true,
        "update": false,
        "delete": false
      }
    }
  ]
}


### Get All Roles
GET {{baseUrl}}/role
Content-Type: application/json


### Get Role By Id
GET {{baseUrl}}/role/6953b7f13480fbe029d78e37
Content-Type: application/json

###update role
PUT {{baseUrl}}/role/6953b7f13480fbe029d78e37
Content-Type: application/json

{
    "name":"Admin Updated"
}

###delete role
DELETE {{baseUrl}}/role/6953b7f13480fbe029d78e37
Content-Type: application/json


### Create Employee
POST {{baseUrl}}/employee
Content-Type: application/json

{
  "name": "Durga Katwal",
  "username": "admin",
  "email":"admin@gmail.com",
  "password": "admin123",
  "role": "6953b7f13480fbe029d78e37",
  "wareHouse": "69520e45fdb59dfe24856b35"
}


### Employee Login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin123"
}


###getAll Employees
GET {{baseUrl}}/employee
Content-Type: application/json
Authorization: Bearer {{token}}


###getEmployeeById
GET {{baseUrl}}/employee/6953b98f7f3482dd7aa808aa
Content-Type: application/json
Authorization: Bearer {{token}}


###Update Employee
PUT {{baseUrl}}/employee/6953b98f7f3482dd7aa808aa
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name":"Durga Katwal Updated"
}

###delete employee
DELETE {{baseUrl}}/employee/6953b98f7f3482dd7aa808aa
Content-Type: application/json
Authorization: Bearer {{token}}
